export const ActionTypes = {
    SET_BOOKS: "SET_BOOKS",
    SELECTED_BOOK: "SELECTED_BOOKS",
    CURRENT_PAGE: "CURRENT_PAGE",
    SET_CART: 'SET_CART',
    ADD_TO_CART: 'ADD_TO_CART',
    DELETE_FROM_CART: 'DELETE_FROM_CART',
    ORDER_ID:"ORDER_ID"
};
